### ISSUE TITLE
Minor Bugs in Installer

### ISSUE THREAD

**Issue by redactedontop** [arithefirst/dotfiles#1]
Hiya, I'm sending a PR to fix these soon, but I wanna preface it by saying:

1. You're always using yay, please use $aur instead.
2. Instead of "|| echo "Command failed." && exit", you should do "|| (echo "Command failed." && exit)", as else you only install the first item.

Thanks,
Alex <3

**Comment by arithefirst** [comment]
Ty for the point-outs, I usually never write in bash which is why it's so terrible lmao. I'm mostly a frontend dev. Issues fixed.
